server:
  port: 8083

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true

#  cloud:
#    gateway:
#      routes:
#        - id: store
#          uri: lb://store
#          predicates:
#            - Path=/store/**
#        - id: consumerModule
#          uri: lb://provider
#          predicates:
#            - Path=/provider/**
